import { TrackedEntity, Signal, Alert, SignalType, SignalSeverity } from './types';

export const mockEntities: TrackedEntity[] = [
  {
    id: '1',
    type: 'founder',
    name: 'Sarah Chen',
    linkedinUrl: 'https://linkedin.com/in/sarahchen',
    currentTitle: 'Building something new',
    company: 'Stealth',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    trackingSince: new Date('2024-11-15'),
    lastChecked: new Date('2024-12-09T10:30:00'),
    stealthScore: 92,
    momentumScore: 78,
  },
  {
    id: '2',
    type: 'founder',
    name: 'Marcus Rodriguez',
    linkedinUrl: 'https://linkedin.com/in/marcusrodriguez',
    currentTitle: 'Founder & CEO',
    company: 'DataFlow AI (Prev: Google)',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    trackingSince: new Date('2024-10-20'),
    lastChecked: new Date('2024-12-09T10:25:00'),
    stealthScore: 34,
    momentumScore: 45,
  },
  {
    id: '3',
    type: 'company',
    name: 'NeuralFlow',
    linkedinUrl: 'https://linkedin.com/company/neuralflow',
    currentTitle: undefined,
    company: undefined,
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=NeuralFlow',
    trackingSince: new Date('2024-12-01'),
    lastChecked: new Date('2024-12-09T10:20:00'),
    stealthScore: 67,
    momentumScore: -23,
  },
  {
    id: '4',
    type: 'founder',
    name: 'Priya Patel',
    linkedinUrl: 'https://linkedin.com/in/priyapatel',
    currentTitle: 'Open to opportunities',
    company: undefined,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    trackingSince: new Date('2024-11-28'),
    lastChecked: new Date('2024-12-09T10:15:00'),
    stealthScore: 88,
    momentumScore: 65,
  },
  {
    id: '5',
    type: 'founder',
    name: 'James Liu',
    linkedinUrl: 'https://linkedin.com/in/jamesliu',
    currentTitle: 'VP Engineering',
    company: 'Stripe',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    trackingSince: new Date('2024-09-10'),
    lastChecked: new Date('2024-12-09T10:10:00'),
    stealthScore: 12,
    momentumScore: 8,
  },
];

export const mockSignals: Signal[] = [
  {
    id: 's1',
    entityId: '1',
    entityName: 'Sarah Chen',
    entityType: 'founder',
    type: 'title_change',
    severity: 'critical',
    title: 'Title changed to stealth mode indicator',
    description: 'Changed title from "VP Product at Uber" to "Building something new"',
    detectedAt: new Date('2024-12-09T08:45:00'),
    previousValue: 'VP Product at Uber',
    currentValue: 'Building something new',
    confidence: 95,
    isRead: false,
  },
  {
    id: 's2',
    entityId: '1',
    entityName: 'Sarah Chen',
    entityType: 'founder',
    type: 'job_removal',
    severity: 'high',
    title: 'Removed job history',
    description: 'Deleted 3 previous positions from profile',
    detectedAt: new Date('2024-12-09T09:12:00'),
    previousValue: '3 positions',
    currentValue: '0 positions',
    confidence: 88,
    isRead: false,
  },
  {
    id: 's3',
    entityId: '1',
    entityName: 'Sarah Chen',
    entityType: 'founder',
    type: 'new_connection_spike',
    severity: 'medium',
    title: 'Connection activity spike',
    description: 'Added 47 new connections in the last 7 days (mostly engineers)',
    detectedAt: new Date('2024-12-08T14:30:00'),
    previousValue: '2,340 connections',
    currentValue: '2,387 connections',
    confidence: 82,
    isRead: true,
  },
  {
    id: 's4',
    entityId: '4',
    entityName: 'Priya Patel',
    entityType: 'founder',
    type: 'open_to_work',
    severity: 'high',
    title: 'Activated "Open to Work" badge',
    description: 'Recently enabled open to work indicator, but with selective visibility',
    detectedAt: new Date('2024-12-09T07:20:00'),
    previousValue: 'Not open to work',
    currentValue: 'Open to work (recruiters only)',
    confidence: 92,
    isRead: false,
  },
  {
    id: 's5',
    entityId: '3',
    entityName: 'NeuralFlow',
    entityType: 'company',
    type: 'team_departure',
    severity: 'critical',
    title: 'Key team members leaving',
    description: '5 senior engineers updated their profiles to "Open to new opportunities"',
    detectedAt: new Date('2024-12-08T16:45:00'),
    confidence: 90,
    isRead: false,
  },
  {
    id: 's6',
    entityId: '3',
    entityName: 'NeuralFlow',
    entityType: 'company',
    type: 'hiring_freeze',
    severity: 'high',
    title: 'Hiring activity stopped',
    description: 'All 8 open job postings removed from LinkedIn',
    detectedAt: new Date('2024-12-07T11:15:00'),
    previousValue: '8 open positions',
    currentValue: '0 open positions',
    confidence: 95,
    isRead: true,
  },
  {
    id: 's7',
    entityId: '2',
    entityName: 'Marcus Rodriguez',
    entityType: 'founder',
    type: 'location_change',
    severity: 'low',
    title: 'Location updated',
    description: 'Changed location from "San Francisco, CA" to "San Francisco Bay Area"',
    detectedAt: new Date('2024-12-05T09:30:00'),
    previousValue: 'San Francisco, CA',
    currentValue: 'San Francisco Bay Area',
    confidence: 70,
    isRead: true,
  },
  {
    id: 's8',
    entityId: '4',
    entityName: 'Priya Patel',
    entityType: 'founder',
    type: 'post_deletion',
    severity: 'medium',
    title: 'Posts removed from profile',
    description: 'Deleted 12 posts related to previous company',
    detectedAt: new Date('2024-12-06T13:20:00'),
    confidence: 75,
    isRead: true,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'a1',
    entityId: '1',
    entityName: 'Sarah Chen',
    signals: [mockSignals[0], mockSignals[1], mockSignals[2]],
    createdAt: new Date('2024-12-09T09:12:00'),
    priority: 95,
    summary: '🚨 High stealth activity detected - Likely starting new venture',
  },
  {
    id: 'a2',
    entityId: '3',
    entityName: 'NeuralFlow',
    signals: [mockSignals[4], mockSignals[5]],
    createdAt: new Date('2024-12-08T16:45:00'),
    priority: 88,
    summary: '⚠️ Company instability - Mass departure and hiring freeze',
  },
  {
    id: 'a3',
    entityId: '4',
    entityName: 'Priya Patel',
    signals: [mockSignals[3], mockSignals[7]],
    createdAt: new Date('2024-12-09T07:20:00'),
    priority: 72,
    summary: '🔍 Potential new venture - Profile cleanup + job seeking',
  },
];

export const getSignalIcon = (type: SignalType): string => {
  const icons: Record<SignalType, string> = {
    title_change: '✏️',
    stealth_mode: '🕶️',
    job_removal: '🗑️',
    hiring_freeze: '❄️',
    team_departure: '👋',
    open_to_work: '💼',
    profile_private: '🔒',
    new_connection_spike: '📈',
    post_deletion: '🧹',
    location_change: '📍',
  };
  return icons[type];
};

export const getSeverityColor = (severity: SignalSeverity): string => {
  const colors: Record<SignalSeverity, string> = {
    critical: 'destructive',
    high: 'destructive',
    medium: 'default',
    low: 'secondary',
  };
  return colors[severity];
};

