import { PortfolioCompany, CompanyUpdate } from './portfolio-types';

export const mockPortfolio: PortfolioCompany[] = [
  {
    id: '1',
    name: 'Superhuman',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SH&backgroundColor=3b82f6',
    stage: 'Series B',
    sector: 'Enterprise SaaS',
    investmentDate: new Date('2022-08-15'),
    ownershipPercent: 8,
    website: 'https://superhuman.com',
    description: 'The fastest email experience ever made',
    healthScore: 92,
    lastUpdate: new Date('2024-12-09'),
  },
  {
    id: '2',
    name: 'Stability AI',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SA&backgroundColor=a855f7',
    stage: 'Series A',
    sector: 'AI/ML',
    investmentDate: new Date('2023-03-20'),
    ownershipPercent: 12,
    website: 'https://stability.ai',
    description: 'Open-source AI models for image, video, and language',
    healthScore: 85,
    lastUpdate: new Date('2024-12-09'),
  },
  {
    id: '3',
    name: 'Mythical Games',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=MG&backgroundColor=ec4899',
    stage: 'Series C+',
    sector: 'Gaming',
    investmentDate: new Date('2021-11-10'),
    ownershipPercent: 5,
    website: 'https://mythical.games',
    description: 'Next-generation game technology studio',
    healthScore: 78,
    lastUpdate: new Date('2024-12-08'),
  },
  {
    id: '4',
    name: 'Kalshi',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=KA&backgroundColor=10b981',
    stage: 'Series A',
    sector: 'FinTech',
    investmentDate: new Date('2023-06-15'),
    ownershipPercent: 15,
    website: 'https://kalshi.com',
    description: 'Regulated exchange for event contracts',
    healthScore: 88,
    lastUpdate: new Date('2024-12-09'),
  },
  {
    id: '5',
    name: 'Formation Bio',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=FB&backgroundColor=ef4444',
    stage: 'Series B',
    sector: 'HealthTech',
    investmentDate: new Date('2022-09-01'),
    ownershipPercent: 10,
    website: 'https://formationbio.com',
    description: 'AI-powered drug development platform',
    healthScore: 82,
    lastUpdate: new Date('2024-12-09'),
  },
  {
    id: '6',
    name: 'Chainguard',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=CG&backgroundColor=f59e0b',
    stage: 'Series A',
    sector: 'Cybersecurity',
    investmentDate: new Date('2023-04-20'),
    ownershipPercent: 14,
    website: 'https://chainguard.dev',
    description: 'Secure software supply chain platform',
    healthScore: 90,
    lastUpdate: new Date('2024-12-09'),
  },
  {
    id: '7',
    name: 'Whop',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=WH&backgroundColor=8b5cf6',
    stage: 'Seed',
    sector: 'E-Commerce',
    investmentDate: new Date('2024-02-10'),
    ownershipPercent: 18,
    website: 'https://whop.com',
    description: 'Platform for selling digital products and access',
    healthScore: 86,
    lastUpdate: new Date('2024-12-08'),
  },
  {
    id: '8',
    name: 'Apeel',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=AP&backgroundColor=22c55e',
    stage: 'Series C+',
    sector: 'ESG/Climate',
    investmentDate: new Date('2021-07-15'),
    ownershipPercent: 6,
    website: 'https://apeel.com',
    description: 'Plant-based protection to extend produce shelf life',
    healthScore: 75,
    lastUpdate: new Date('2024-12-07'),
  },
  {
    id: '9',
    name: 'Beacons AI',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=BA&backgroundColor=06b6d4',
    stage: 'Seed',
    sector: 'Consumer/Creator',
    investmentDate: new Date('2023-11-20'),
    ownershipPercent: 16,
    website: 'https://beacons.ai',
    description: 'All-in-one creator platform with AI tools',
    healthScore: 84,
    lastUpdate: new Date('2024-12-09'),
  },
  {
    id: '10',
    name: 'VeHo',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=VH&backgroundColor=f97316',
    stage: 'Series A',
    sector: 'Logistics',
    investmentDate: new Date('2023-05-10'),
    ownershipPercent: 13,
    website: 'https://veho.co',
    description: 'Next-gen last-mile delivery powered by drivers',
    healthScore: 79,
    lastUpdate: new Date('2024-12-08'),
  },
];

export const mockUpdates: CompanyUpdate[] = [
  {
    id: 'u1',
    companyId: '2',
    companyName: 'Stability AI',
    type: 'news',
    title: 'Stability AI Releases New Open-Source Model',
    summary: 'Launched Stable Diffusion 3.0 with improved image quality and faster processing. Community response overwhelmingly positive with 100K+ downloads in first week.',
    source: 'TechCrunch',
    date: new Date('2024-12-09T10:00:00'),
    sentiment: 'positive',
  },
  {
    id: 'u2',
    companyId: '1',
    companyName: 'Superhuman',
    type: 'product',
    title: 'AI-Powered Email Writing Released',
    summary: 'New AI assistant feature helps users write emails 3x faster. Early access users report 40% increase in email productivity.',
    source: 'Product Hunt',
    date: new Date('2024-12-09T08:30:00'),
    sentiment: 'positive',
  },
  {
    id: 'u3',
    companyId: '6',
    companyName: 'Chainguard',
    type: 'hiring',
    title: 'Former Google Security Lead Joins as CTO',
    summary: 'Hired renowned security expert from Google Cloud. Signals major expansion of engineering team to 50+ by Q2.',
    source: 'LinkedIn',
    date: new Date('2024-12-08T15:00:00'),
    sentiment: 'positive',
  },
  {
    id: 'u4',
    companyId: '4',
    companyName: 'Kalshi',
    type: 'funding',
    title: 'Series B Round in Discussion',
    summary: 'Sources indicate Kalshi in talks for $100M+ Series B at $1B valuation. Sequoia and a16z showing strong interest.',
    source: 'The Information',
    date: new Date('2024-12-08T11:00:00'),
    sentiment: 'positive',
  },
  {
    id: 'u5',
    companyId: '8',
    companyName: 'Apeel',
    type: 'market',
    title: 'Climate Tech Funding Slows',
    summary: 'Overall climate tech sector seeing 30% reduction in funding. Apeel\'s proven revenue model positions it well despite headwinds.',
    source: 'Bloomberg',
    date: new Date('2024-12-07T14:00:00'),
    sentiment: 'neutral',
  },
  {
    id: 'u6',
    companyName: 'Mythical Games',
    type: 'news',
    title: 'NFL Rivals Game Surpasses 1M Users',
    summary: 'Popular NFL mobile game crosses major milestone. Revenue up 150% QoQ, making it top-grossing sports game.',
    source: 'VentureBeat',
    date: new Date('2024-12-07T09:00:00'),
    sentiment: 'positive',
    companyId: '3',
    id: 'u7',
  },
  {
    id: 'u8',
    companyId: '9',
    companyName: 'Beacons AI',
    type: 'product',
    title: 'AI Store Builder Launches',
    summary: 'New AI-powered storefront builder lets creators launch e-commerce in minutes. 5,000 stores created in first 48 hours.',
    source: 'Company Blog',
    date: new Date('2024-12-06T16:00:00'),
    sentiment: 'positive',
  },
  {
    id: 'u9',
    companyId: '7',
    companyName: 'Whop',
    type: 'news',
    title: 'Whop Hits $100M GMV Milestone',
    summary: 'Platform processes $100M in total sales. Creator payouts growing 300% YoY.',
    source: 'Forbes',
    date: new Date('2024-12-06T10:00:00'),
    sentiment: 'positive',
  },
  {
    id: 'u10',
    companyId: '5',
    companyName: 'Formation Bio',
    type: 'news',
    title: 'Phase II Trial Shows Promising Results',
    summary: 'Lead drug candidate shows 60% efficacy in Phase II trials. FDA fast-track designation likely.',
    source: 'BioPharma Dive',
    date: new Date('2024-12-05T14:30:00'),
    sentiment: 'positive',
  },
  {
    id: 'u11',
    companyId: '10',
    companyName: 'VeHo',
    type: 'market',
    title: 'Last-Mile Delivery Competition Intensifies',
    summary: 'Amazon expanding same-day delivery. VeHo\'s driver-first model provides differentiation but faces margin pressure.',
    source: 'Reuters',
    date: new Date('2024-12-05T11:00:00'),
    sentiment: 'neutral',
  },
];

export const getCompanyUpdates = (companyId: string): CompanyUpdate[] => {
  return mockUpdates.filter(update => update.companyId === companyId);
};

export const getRecentUpdates = (limit: number = 10): CompanyUpdate[] => {
  return [...mockUpdates]
    .sort((a, b) => b.date.getTime() - a.date.getTime())
    .slice(0, limit);
};
