import { Person } from './simple-types';

export const mockPeople: Person[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    currentTitle: 'Building something new',
    previousTitle: 'VP Product',
    company: 'Stealth',
    previousCompany: 'Coinbase',
    location: 'San Francisco, CA',
    linkedinUrl: 'https://linkedin.com/in/sarahchen',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    lastUpdated: new Date('2024-12-08'),
    isSaved: false,
    stealthIndicators: ['Title change to "building something new"', 'Company changed to "Stealth"'],
  },
  {
    id: '2',
    name: 'Marcus Rodriguez',
    currentTitle: 'Exploring new opportunities',
    previousTitle: 'Engineering Director',
    company: 'Stealth',
    previousCompany: 'Coinbase',
    location: 'New York, NY',
    linkedinUrl: 'https://linkedin.com/in/marcus',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    lastUpdated: new Date('2024-12-07'),
    isSaved: false,
    stealthIndicators: ['Recently left Coinbase', 'Vague new title'],
  },
  {
    id: '3',
    name: 'Priya Patel',
    currentTitle: 'Co-founder',
    previousTitle: 'Head of Product',
    company: 'Stealth Startup',
    previousCompany: 'Stripe',
    location: 'San Francisco, CA',
    linkedinUrl: 'https://linkedin.com/in/priya',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    lastUpdated: new Date('2024-12-09'),
    isSaved: true,
    stealthIndicators: ['New co-founder role', 'Company listed as "Stealth Startup"'],
  },
  {
    id: '4',
    name: 'Alex Kim',
    currentTitle: 'Founder',
    previousTitle: 'Senior Engineering Manager',
    company: 'Stealth',
    previousCompany: 'Uber',
    location: 'Austin, TX',
    linkedinUrl: 'https://linkedin.com/in/alexkim',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    lastUpdated: new Date('2024-12-06'),
    isSaved: false,
    stealthIndicators: ['Left Uber', 'Now listing as "Founder"'],
  },
  {
    id: '5',
    name: 'Jordan Lee',
    currentTitle: 'Working on something exciting',
    previousTitle: 'VP Engineering',
    company: 'Confidential',
    previousCompany: 'Coinbase',
    location: 'Remote',
    linkedinUrl: 'https://linkedin.com/in/jordan',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    lastUpdated: new Date('2024-12-05'),
    isSaved: false,
    stealthIndicators: ['Vague title', 'Company set to "Confidential"', 'Recently left Coinbase'],
  },
  {
    id: '6',
    name: 'Taylor Martinez',
    currentTitle: 'Founder & CEO',
    previousTitle: 'Product Lead',
    company: 'Stealth',
    previousCompany: 'Meta',
    location: 'Los Angeles, CA',
    linkedinUrl: 'https://linkedin.com/in/taylor',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor',
    lastUpdated: new Date('2024-12-04'),
    isSaved: true,
    stealthIndicators: ['New founder role', 'Left Meta recently'],
  },
  {
    id: '7',
    name: 'Chris Wong',
    currentTitle: 'Building in AI',
    previousTitle: 'ML Engineer',
    company: 'Stealth',
    previousCompany: 'OpenAI',
    location: 'San Francisco, CA',
    linkedinUrl: 'https://linkedin.com/in/chris',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chris',
    lastUpdated: new Date('2024-12-09'),
    isSaved: false,
    stealthIndicators: ['Left OpenAI', '"Building in AI" title'],
  },
  {
    id: '8',
    name: 'Sam Nguyen',
    currentTitle: 'Stealth Founder',
    previousTitle: 'Director of Engineering',
    company: 'Stealth',
    previousCompany: 'Coinbase',
    location: 'San Francisco, CA',
    linkedinUrl: 'https://linkedin.com/in/sam',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sam',
    lastUpdated: new Date('2024-12-03'),
    isSaved: false,
    stealthIndicators: ['Explicitly says "Stealth Founder"', 'Recently departed Coinbase'],
  },
];

export const companies = [
  'Coinbase',
  'Stripe',
  'OpenAI',
  'Anthropic',
  'Meta',
  'Google',
  'Apple',
  'Amazon',
  'Microsoft',
  'Uber',
  'Airbnb',
  'Netflix',
];

export const roles = [
  'VP',
  'Director',
  'Head of',
  'Engineering Manager',
  'Product Manager',
  'Founder',
  'CTO',
  'CEO',
];

export const stealthSignals = [
  'Title contains "building", "exploring", "stealth"',
  'Company changed to "Stealth", "Confidential", etc.',
  'Recently left a major company',
  'New "Founder" or "Co-founder" title',
];

